// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type ContactoDocumentDataSlicesSlice =
  | FormularioContactoPageSlice
  | ContactoEmailsSlice
  | HeroContactSlice;

/**
 * Content for Contacto documents
 */
interface ContactoDocumentData {
  /**
   * Slice Zone field in *Contacto*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactoDocumentDataSlicesSlice> /**
   * Meta Title field in *Contacto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contacto.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contacto*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contacto.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contacto*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contacto document from Prismic
 *
 * - **API ID**: `contacto`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactoDocumentData>,
    "contacto",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | ProductosSlice
  | ServicesSlice
  | ContactoSlice
  | ComercialesSlice
  | DistribuidoresSlice
  | ServiciosSlice
  | CotizacionesSlice
  | SliderSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type ServiciosDocumentDataSlicesSlice = HeroServicesSlice | ServicesSlice;

/**
 * Content for Servicios documents
 */
interface ServiciosDocumentData {
  /**
   * Slice Zone field in *Servicios*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ServiciosDocumentDataSlicesSlice> /**
   * Meta Title field in *Servicios*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: servicios.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Servicios*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: servicios.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Servicios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Servicios document from Prismic
 *
 * - **API ID**: `servicios`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiciosDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServiciosDocumentData>,
    "servicios",
    Lang
  >;

export type AllDocumentTypes =
  | ContactoDocument
  | HomeDocument
  | ServiciosDocument;

/**
 * Item in *Comerciales → Default → Primary → Comerciales*
 */
export interface ComercialesSliceDefaultPrimaryComercialesItem {
  /**
   * Imagen field in *Comerciales → Default → Primary → Comerciales*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: comerciales.default.primary.comerciales[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Zona field in *Comerciales → Default → Primary → Comerciales*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: comerciales.default.primary.comerciales[].zone
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  zone: prismic.ImageField<never>;

  /**
   * Nombre field in *Comerciales → Default → Primary → Comerciales*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comerciales.default.primary.comerciales[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Posición field in *Comerciales → Default → Primary → Comerciales*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comerciales.default.primary.comerciales[].position
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  position: prismic.KeyTextField;

  /**
   * Titulo field in *Comerciales → Default → Primary → Comerciales*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comerciales.default.primary.comerciales[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Teléfono field in *Comerciales → Default → Primary → Comerciales*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comerciales.default.primary.comerciales[].phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;
}

/**
 * Primary content in *Comerciales → Default → Primary*
 */
export interface ComercialesSliceDefaultPrimary {
  /**
   * Zona Comercial field in *Comerciales → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comerciales.default.primary.zona_comercial
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  zona_comercial: prismic.RichTextField;

  /**
   * Texto field in *Comerciales → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comerciales.default.primary.texto
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texto: prismic.RichTextField;

  /**
   * Comerciales field in *Comerciales → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: comerciales.default.primary.comerciales[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  comerciales: prismic.GroupField<
    Simplify<ComercialesSliceDefaultPrimaryComercialesItem>
  >;
}

/**
 * Default variation for Comerciales Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComercialesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ComercialesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Comerciales*
 */
type ComercialesSliceVariation = ComercialesSliceDefault;

/**
 * Comerciales Shared Slice
 *
 * - **API ID**: `comerciales`
 * - **Description**: Comerciales
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ComercialesSlice = prismic.SharedSlice<
  "comerciales",
  ComercialesSliceVariation
>;

/**
 * Primary content in *Contacto → Default → Primary*
 */
export interface ContactoSliceDefaultPrimary {
  /**
   * Titulo field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Ciudad field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.city
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  city: prismic.KeyTextField;

  /**
   * Dirección field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.address
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Teléfono Oficina field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.office_phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  office_phone: prismic.KeyTextField;

  /**
   * Teléfono field in *Contacto → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;
}

/**
 * Default variation for Contacto Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contacto*
 */
type ContactoSliceVariation = ContactoSliceDefault;

/**
 * Contacto Shared Slice
 *
 * - **API ID**: `contacto`
 * - **Description**: Contacto
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactoSlice = prismic.SharedSlice<
  "contacto",
  ContactoSliceVariation
>;

/**
 * Item in *ContactoEmails → Default → Primary → Email*
 */
export interface ContactoEmailsSliceDefaultPrimaryEmailItem {
  /**
   * Email field in *ContactoEmails → Default → Primary → Email*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto_emails.default.primary.email[].email_direction
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_direction: prismic.KeyTextField;

  /**
   * Area field in *ContactoEmails → Default → Primary → Email*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto_emails.default.primary.email[].area
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  area: prismic.SelectField<
    | "ADMINISTRACION, CONTABILIDAD Y FINANZAS"
    | "FINANZAS"
    | "CONTABLE E IMPOSITIVA"
    | "GRANOS"
    | "INSUMOS"
    | "PRODUCCIÓN AGROPECUARIA"
    | "PLANTA DE ACOPIO"
    | "SUCURSAL DE LOS QUIRQUINCHOS"
    | "RSE"
  >;
}

/**
 * Primary content in *ContactoEmails → Default → Primary*
 */
export interface ContactoEmailsSliceDefaultPrimary {
  /**
   * Email field in *ContactoEmails → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contacto_emails.default.primary.email[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  email: prismic.GroupField<
    Simplify<ContactoEmailsSliceDefaultPrimaryEmailItem>
  >;
}

/**
 * Default variation for ContactoEmails Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactoEmailsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactoEmailsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactoEmails*
 */
type ContactoEmailsSliceVariation = ContactoEmailsSliceDefault;

/**
 * ContactoEmails Shared Slice
 *
 * - **API ID**: `contacto_emails`
 * - **Description**: ContactoEmails
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactoEmailsSlice = prismic.SharedSlice<
  "contacto_emails",
  ContactoEmailsSliceVariation
>;

/**
 * Primary content in *Cotizaciones → Default → Primary*
 */
export interface CotizacionesSliceDefaultPrimary {
  /**
   * Titulo field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Fondo BCR field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.bg_bcr
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bg_bcr: prismic.ImageField<never>;

  /**
   * Titulo BCR field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.title_bcr
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_bcr: prismic.KeyTextField;

  /**
   * Subtitulo BCR field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.subtitle_bcr
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle_bcr: prismic.KeyTextField;

  /**
   * Fondo Promedios field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.bg_promedios
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bg_promedios: prismic.ImageField<never>;

  /**
   * Titulo Promedios field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.title_promedios
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_promedios: prismic.KeyTextField;

  /**
   * Texto Promedios field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.text_promedios
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_promedios: prismic.KeyTextField;

  /**
   * Fondo Precios field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.bg_precios
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  bg_precios: prismic.ImageField<never>;

  /**
   * Titulo Precios field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.title_prices
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_prices: prismic.KeyTextField;

  /**
   * Texto Precios field in *Cotizaciones → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cotizaciones.default.primary.text_prices
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_prices: prismic.KeyTextField;
}

/**
 * Default variation for Cotizaciones Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CotizacionesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CotizacionesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cotizaciones*
 */
type CotizacionesSliceVariation = CotizacionesSliceDefault;

/**
 * Cotizaciones Shared Slice
 *
 * - **API ID**: `cotizaciones`
 * - **Description**: Cotizaciones
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CotizacionesSlice = prismic.SharedSlice<
  "cotizaciones",
  CotizacionesSliceVariation
>;

/**
 * Item in *Distribuidores → Default → Primary → Logos*
 */
export interface DistribuidoresSliceDefaultPrimaryLogosItem {
  /**
   * Logo field in *Distribuidores → Default → Primary → Logos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: distribuidores.default.primary.logos[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link field in *Distribuidores → Default → Primary → Logos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: distribuidores.default.primary.logos[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Distribuidores → Default → Primary*
 */
export interface DistribuidoresSliceDefaultPrimary {
  /**
   * Titulo field in *Distribuidores → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: distribuidores.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *Distribuidores → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: distribuidores.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Logos field in *Distribuidores → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: distribuidores.default.primary.logos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  logos: prismic.GroupField<
    Simplify<DistribuidoresSliceDefaultPrimaryLogosItem>
  >;
}

/**
 * Default variation for Distribuidores Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DistribuidoresSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DistribuidoresSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Distribuidores*
 */
type DistribuidoresSliceVariation = DistribuidoresSliceDefault;

/**
 * Distribuidores Shared Slice
 *
 * - **API ID**: `distribuidores`
 * - **Description**: Distribuidores
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DistribuidoresSlice = prismic.SharedSlice<
  "distribuidores",
  DistribuidoresSliceVariation
>;

/**
 * Primary content in *FormularioContactoPage → Default → Primary*
 */
export interface FormularioContactoPageSliceDefaultPrimary {
  /**
   * Titulo field in *FormularioContactoPage → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: formulario_contacto_page.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for FormularioContactoPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormularioContactoPageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormularioContactoPageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FormularioContactoPage*
 */
type FormularioContactoPageSliceVariation = FormularioContactoPageSliceDefault;

/**
 * FormularioContactoPage Shared Slice
 *
 * - **API ID**: `formulario_contacto_page`
 * - **Description**: FormularioContactoPage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormularioContactoPageSlice = prismic.SharedSlice<
  "formulario_contacto_page",
  FormularioContactoPageSliceVariation
>;

/**
 * Primary content in *HeroContact → Default → Primary*
 */
export interface HeroContactSliceDefaultPrimary {
  /**
   * Imagen field in *HeroContact → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_contact.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroContact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroContact*
 */
type HeroContactSliceVariation = HeroContactSliceDefault;

/**
 * HeroContact Shared Slice
 *
 * - **API ID**: `hero_contact`
 * - **Description**: HeroContact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroContactSlice = prismic.SharedSlice<
  "hero_contact",
  HeroContactSliceVariation
>;

/**
 * Primary content in *HeroServices → Default → Primary*
 */
export interface HeroServicesSliceDefaultPrimary {
  /**
   * Imagen field in *HeroServices → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_services.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titulo field in *HeroServices → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_services.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *HeroServices → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_services.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for HeroServices Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroServices*
 */
type HeroServicesSliceVariation = HeroServicesSliceDefault;

/**
 * HeroServices Shared Slice
 *
 * - **API ID**: `hero_services`
 * - **Description**: HeroServices
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroServicesSlice = prismic.SharedSlice<
  "hero_services",
  HeroServicesSliceVariation
>;

/**
 * Primary content in *Productos → Default → Primary*
 */
export interface ProductosSliceDefaultPrimary {
  /**
   * Imagen field in *Productos → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: productos.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titulo field in *Productos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: productos.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *Productos → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: productos.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Productos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Productos*
 */
type ProductosSliceVariation = ProductosSliceDefault;

/**
 * Productos Shared Slice
 *
 * - **API ID**: `productos`
 * - **Description**: Productos
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductosSlice = prismic.SharedSlice<
  "productos",
  ProductosSliceVariation
>;

/**
 * Item in *Services → Default → Primary → Servicios*
 */
export interface ServicesSliceDefaultPrimaryServicesItem {
  /**
   * Imagen field in *Services → Default → Primary → Servicios*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titulo field in *Services → Default → Primary → Servicios*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Texto field in *Services → Default → Primary → Servicios*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Color de fondo field in *Services → Default → Primary → Servicios*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[].bg_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  bg_color: prismic.ColorField;
}

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Servicios field in *Services → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<
    Simplify<ServicesSliceDefaultPrimaryServicesItem>
  >;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Item in *Servicios → Default → Primary → Lista de servicios*
 */
export interface ServiciosSliceDefaultPrimaryServiceListItem {
  /**
   * Titulo field in *Servicios → Default → Primary → Lista de servicios*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.default.primary.service_list[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Servicios → Default → Primary*
 */
export interface ServiciosSliceDefaultPrimary {
  /**
   * Imágen field in *Servicios → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titulo field in *Servicios → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Lista de servicios field in *Servicios → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: servicios.default.primary.service_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  service_list: prismic.GroupField<
    Simplify<ServiciosSliceDefaultPrimaryServiceListItem>
  >;
}

/**
 * Default variation for Servicios Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiciosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiciosSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Servicios*
 */
type ServiciosSliceVariation = ServiciosSliceDefault;

/**
 * Servicios Shared Slice
 *
 * - **API ID**: `servicios`
 * - **Description**: Servicios
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiciosSlice = prismic.SharedSlice<
  "servicios",
  ServiciosSliceVariation
>;

/**
 * Item in *Slider → Default → Primary → Slide*
 */
export interface SliderSliceDefaultPrimarySlideItem {
  /**
   * Imagen field in *Slider → Default → Primary → Slide*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slide[].imagen
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  imagen: prismic.ImageField<never>;

  /**
   * Titulo field in *Slider → Default → Primary → Slide*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slide[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *Slider → Default → Primary → Slide*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slide[].texto
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  texto: prismic.RichTextField;
}

/**
 * Primary content in *Slider → Default → Primary*
 */
export interface SliderSliceDefaultPrimary {
  /**
   * Slide field in *Slider → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.default.primary.slide[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  slide: prismic.GroupField<Simplify<SliderSliceDefaultPrimarySlideItem>>;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ContactoDocument,
      ContactoDocumentData,
      ContactoDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      ServiciosDocument,
      ServiciosDocumentData,
      ServiciosDocumentDataSlicesSlice,
      AllDocumentTypes,
      ComercialesSlice,
      ComercialesSliceDefaultPrimaryComercialesItem,
      ComercialesSliceDefaultPrimary,
      ComercialesSliceVariation,
      ComercialesSliceDefault,
      ContactoSlice,
      ContactoSliceDefaultPrimary,
      ContactoSliceVariation,
      ContactoSliceDefault,
      ContactoEmailsSlice,
      ContactoEmailsSliceDefaultPrimaryEmailItem,
      ContactoEmailsSliceDefaultPrimary,
      ContactoEmailsSliceVariation,
      ContactoEmailsSliceDefault,
      CotizacionesSlice,
      CotizacionesSliceDefaultPrimary,
      CotizacionesSliceVariation,
      CotizacionesSliceDefault,
      DistribuidoresSlice,
      DistribuidoresSliceDefaultPrimaryLogosItem,
      DistribuidoresSliceDefaultPrimary,
      DistribuidoresSliceVariation,
      DistribuidoresSliceDefault,
      FormularioContactoPageSlice,
      FormularioContactoPageSliceDefaultPrimary,
      FormularioContactoPageSliceVariation,
      FormularioContactoPageSliceDefault,
      HeroContactSlice,
      HeroContactSliceDefaultPrimary,
      HeroContactSliceVariation,
      HeroContactSliceDefault,
      HeroServicesSlice,
      HeroServicesSliceDefaultPrimary,
      HeroServicesSliceVariation,
      HeroServicesSliceDefault,
      ProductosSlice,
      ProductosSliceDefaultPrimary,
      ProductosSliceVariation,
      ProductosSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimaryServicesItem,
      ServicesSliceDefaultPrimary,
      ServicesSliceVariation,
      ServicesSliceDefault,
      ServiciosSlice,
      ServiciosSliceDefaultPrimaryServiceListItem,
      ServiciosSliceDefaultPrimary,
      ServiciosSliceVariation,
      ServiciosSliceDefault,
      SliderSlice,
      SliderSliceDefaultPrimarySlideItem,
      SliderSliceDefaultPrimary,
      SliderSliceVariation,
      SliderSliceDefault,
    };
  }
}
