// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  comerciales: dynamic(() => import("./Comerciales")),
  contacto: dynamic(() => import("./Contacto")),
  cotizaciones: dynamic(() => import("./Cotizaciones")),
  distribuidores: dynamic(() => import("./Distribuidores")),
  hero_services: dynamic(() => import("./HeroServices")),
  services: dynamic(() => import("./Services")),
  servicios: dynamic(() => import("./Servicios")),
  slider: dynamic(() => import("./Slider")),
};
